services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend_app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"   # ✅ FIXED
    container_name: frontend_app
    depends_on:
      - backend